### ISSUE TITLE
Ajuda para instalar.

### ISSUE THREAD

**Issue by UelioNobre** [Arthur-bl-dev/arthurbarros-portfolio#1]
### Fala Arthur!

Tentei baixar este projeto e executar. Acho que deu alguma coisa errada.
Poderia me ajudar a instalar esse projeto?

Para chegar até o erro, percorri os seguintes passos:

- `https://github.com/Arthur-bl-dev/arthurbarros-portfolio.git`

E depois executei:

- `npm install`

A mensagem que recebi no console.

<img width="713" alt="Captura de Tela 2022-06-11 às 18 22 58" src="https://user-images.githubusercontent.com/5035293/173205321-e5bf98e6-fc69-47f7-b8d5-86c429b31adf.png">

.o/

**Comment by Arthur-bl-dev** [comment]
> ### Fala Arthur!
> Tentei baixar este projeto e executar. Acho que deu alguma coisa errada. Poderia me ajudar a instalar esse projeto?
> 
> Para chegar até o erro, percorri os seguintes passos:
> 
> * `https://github.com/Arthur-bl-dev/arthurbarros-portfolio.git`
> 
> E depois executei:
> 
> * `npm install`
> 
> A mensagem que recebi no console.
> 
> <img alt="Captura de Tela 2022-06-11 às 18 22 58" width="713" src="https://user-images.githubusercontent.com/5035293/173205321-e5bf98e6-fc69-47f7-b8d5-86c429b31adf.png">
> 
> .o/

Tente usando:
`yarn install`

**Comment by UelioNobre** [comment]
Show!
Deu certo! .o/
